server:
  port: 8080

# 数据源的配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdemo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: hanxu
# SpringBoot2.0默认使用HikariCP做为连接池，其性能速度都远高于其他，所以不必手动配置连接池信息。

# mybatis配置

# 配置输出sql语句，可选择不同输出流
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
