server:
  port: 8080

# 数据源的配置
# 如果你使用的mysql驱动（pom依赖）为新版本（或5以上的版本），那么就必须跟上时区信息：serverTimezone=UTC（标准时区，相对我们会慢8小时，所以需要选择上海时区serverTimezone=Asia/Shanghai，但是我没有用到时间，就不改了）
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdemo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: hanxu
# SpringBoot2.0默认使用HikariCP做为连接池，其性能速度都远高于其他，所以不必手动配置连接池信息。

# mybatis配置

# 配置输出sql语句，可选择不同输出流
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
