server:
  port: 8080

# \u6570\u636E\u6E90
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdemo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: hanxu
# SpringBoot2.0\u9ED8\u8BA4\u914D\u7F6EHikariCP\u4F5C\u4E3A\u6570\u636E\u5E93\u8FDE\u63A5\u6C60

# mybatis\u914D\u7F6E  \u4E0D\u7528\u914D\uFF0C\u56E0\u4E3A\u5DF2\u7ECF\u6CA1\u6709mapper.xml\u6587\u4EF6\u4E86

# \u8F93\u51FAsql\u8BED\u53E5\uFF0C\u53EF\u4EE5\u4F7F\u7528\u65E5\u5FD7\u8F93\u51FA\uFF0C\u4E5F\u53EF\u4EE5\u8F93\u51FA\u6807\u51C6\u8F93\u51FA\u6D41
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl