
hx:
  ctj:
    name: xxx
    pro: hhh
    hlist:
      - www
      - search
      - manager
      - api
    hstr: strstrstr

hh:
  xxx:
    name: xxxxx
    sg: 186
    tz: 70
    jj: 18
  hlist:
    - qqq
    - www
    - eee
